In [9]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import geopandas as gpd
import folium
import os
from pathlib import Path

# set cwd to src
os.chdir('../src')
from utils import *

data_path = Path('../data')

In [11]:
trips_df = pd.read_csv(data_path / 'dest_trips_OKC_Six_Flags_2023-01-01_to_2024-01-30.csv')
polygon_gdf = gpd.read_file(data_path / 'six_flags_polygons.csv')

In [12]:
display(trips_df)

,year,month,day,hour,minute,second,orig_qk17,dest_qk17,start_lat,start_lon,end_lat,end_lon,count,trip_id,is_moving
0,2023,1,27,14,20,8,2311212101230110,2311212100110100,35.351936,-97.497913,35.460583,-97.591377,1,d7ff1ed49610f830c344d577cf96649c,1
1,2023,1,5,18,16,24,2311212101110311,2311210322332330,35.449962,-97.405401,35.465044,-97.583579,1,753da81fa184b0a826ffbb0b462bbf05,1
2,2023,1,3,14,27,57,2311210322323210,2311210322332320,35.469146,-97.618931,35.464130,-97.588830,1,d97db07594165b6cf58b8d38171431da,1
3,2023,1,22,20,31,8,2311212101230133,2311210322332331,35.345863,-97.495168,35.463981,-97.581652,1,ccb6e742eae2c0b46842093fb586784b,1
4,2023,1,30,12,26,17,2311212011310300,2311212100110011,35.379820,-97.766756,35.459395,-97.592072,1,866cd151ce18aed2886236c9dc0f888f,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11288,2023,1,23,13,8,50,2311212101222100,2311212100110011,35.333590,-97.547210,35.458611,-97.593395,1,2fe0e128686c94febf6883fb70836941,1
11289,2023,1,8,15,11,37,2311123123033100,2311212100110010,37.247266,-93.261852,35.459262,-97.595403,1,4317d3bf04e60ad1cafcf28a4413621f,1
11290,2023,1,23,14,20,39,2311210321232202,2311212100110112,35.609263,-97.513270,35.457740,-97.584458,1,4b97563a54a645adf6c44dbe37adbbc9,1
11291,2023,1,13,14,29,40,2311210322332013,2311210322332300,35.476028,-97.592716,35.467652,-97.590306,1,aa768502867a1bf89d7d8f6a4e94320c,1
11292,2023,1,5,13,18,56,2311210322322000,2311210322332320,35.478340,-97.643885,35.463482,-97.591013,1,5022f9cd5bd9fe7b486bc3716f0e5c73,1